### ISSUE TITLE
[driver][socket] Lslidar poll() timeout Ubuntu 20.04 RO2 Foxy

### ISSUE THREAD

**Issue by GoktugGurler95** [Lslidar/Lslidar_ROS2_driver#4]
Hello, 
I compiled the ros2 Foxy package. package compiled compiled without any problems. When I run launch I get the following error. 
"lslidar poll() timeout"  lidar default ip is 192.168.1.200 and my computer's ip is 192.168.1.102. and I couldn't get any data from your device. what is the problem? can anyone help?

**Comment by cirillom** [comment]
I am still facing this problem, how did you fix it?
